package com.bani.medreminder;
import android.app.*; import android.content.*; import android.media.*; import android.net.Uri; import android.os.*;
public class AlarmService extends Service {
 private MediaPlayer player; public static final String CHANNEL="med_alarm";
 @Override public void onCreate(){super.onCreate();createChannel();}
 @Override public int onStartCommand(Intent intent,int flags,int startId){ long medId=intent.getLongExtra("medId",-1);Med m=new Db(this).get(medId);if(m==null){stopSelf();return START_NOT_STICKY;}Intent full=new Intent(this,AlarmActivity.class).putExtra("medId",medId).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TOP);PendingIntent fullPi=PendingIntent.getActivity(this,(int)medId,full,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);Notification n=new Notification.Builder(this,CHANNEL).setSmallIcon(android.R.drawable.ic_lock_idle_alarm).setContentTitle("وقت مصرف: "+m.name).setContentText(m.dose==null?"":m.dose).setCategory(Notification.CATEGORY_ALARM).setPriority(Notification.PRIORITY_MAX).setOngoing(true).setFullScreenIntent(fullPi,true).setContentIntent(fullPi).build();startForeground((int)(20000+(medId%10000)),n);try{Uri uri=RingtoneManager.getDefaultUri(RingtoneManager.TYPE_ALARM);player=MediaPlayer.create(this,uri);if(player!=null){player.setLooping(true);player.start();}}catch(Exception ignored){}Vibrator vibrator=(Vibrator)getSystemService(Context.VIBRATOR_SERVICE);if(vibrator!=null)vibrator.vibrate(VibrationEffect.createWaveform(new long[]{0,600,250,600},0));try{startActivity(full);}catch(Exception ignored){}return START_NOT_STICKY; }
 private void createChannel(){NotificationManager nm=(NotificationManager)getSystemService(Context.NOTIFICATION_SERVICE);NotificationChannel ch=new NotificationChannel(CHANNEL,"یادآور دارو",NotificationManager.IMPORTANCE_HIGH);ch.setDescription("هشدار زمان مصرف دارو");ch.enableVibration(true);ch.setLockscreenVisibility(Notification.VISIBILITY_PUBLIC);nm.createNotificationChannel(ch);}
 @Override public void onDestroy(){if(player!=null){try{player.stop();}catch(Exception ignored){}player.release();}super.onDestroy();}
 @Override public IBinder onBind(Intent i){return null;}
}
