package com.bani.medreminder;
import android.Manifest; import android.app.*; import android.content.*; import android.content.pm.PackageManager; import android.graphics.Color; import android.net.Uri; import android.os.*; import android.provider.Settings; import android.view.*; import android.widget.*; import java.text.SimpleDateFormat; import java.util.*;
public class MainActivity extends Activity { Db db;int hour=-1,minute=-1;LinearLayout list;Button timeButton,photoButton,removePhoto;ImageView photoPreview;String selectedImageUri="";
 @Override protected void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);db=new Db(this);list=findViewById(R.id.list);timeButton=findViewById(R.id.timeButton);photoButton=findViewById(R.id.photoButton);removePhoto=findViewById(R.id.removePhoto);photoPreview=findViewById(R.id.photoPreview);if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},10);timeButton.setOnClickListener(v->{Calendar c=Calendar.getInstance();new TimePickerDialog(this,(view,h,m)->{hour=h;minute=m;timeButton.setText(String.format(Locale.US,"%02d:%02d",h,m));},c.get(Calendar.HOUR_OF_DAY),c.get(Calendar.MINUTE),true).show();});photoButton.setOnClickListener(v->pickPhoto());removePhoto.setOnClickListener(v->clearPhoto());findViewById(R.id.save).setOnClickListener(v->save());findViewById(R.id.exactSettings).setOnClickListener(v->openExactAlarmSettings());render();}
 void pickPhoto(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("image/*");startActivityForResult(i,20);}
 @Override protected void onActivityResult(int requestCode,int resultCode,Intent data){super.onActivityResult(requestCode,resultCode,data);if(requestCode==20&&resultCode==RESULT_OK&&data!=null&&data.getData()!=null){Uri u=data.getData();try{getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}selectedImageUri=u.toString();photoPreview.setImageURI(u);photoPreview.setVisibility(View.VISIBLE);removePhoto.setVisibility(View.VISIBLE);photoButton.setText("📷 تغییر عکس دارو");}}
 void clearPhoto(){selectedImageUri="";photoPreview.setImageDrawable(null);photoPreview.setVisibility(View.GONE);removePhoto.setVisibility(View.GONE);photoButton.setText("📷 انتخاب عکس دارو");}
 void save(){EditText name=findViewById(R.id.name),dose=findViewById(R.id.dose),stock=findViewById(R.id.stock);String n=name.getText().toString().trim();if(n.isEmpty()||hour<0){Toast.makeText(this,"نام دارو و ساعت الزامی است",Toast.LENGTH_SHORT).show();return;}int s=0;try{s=Integer.parseInt(stock.getText().toString().trim());}catch(Exception ignored){}long id=db.add(n,dose.getText().toString().trim(),hour,minute,s,selectedImageUri);Med m=db.get(id);AlarmScheduler.schedule(this,m);name.setText("");dose.setText("");stock.setText("");hour=minute=-1;timeButton.setText("انتخاب ساعت");clearPhoto();render();}
 void render(){list.removeAllViews();String today=new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date());for(Med m:db.all()){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(28,22,28,22);card.setBackgroundColor(0xff1e293b);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.setMargins(0,0,0,18);card.setLayoutParams(cp);if(m.imageUri!=null&&!m.imageUri.isEmpty()){ImageView img=new ImageView(this);img.setLayoutParams(new LinearLayout.LayoutParams(-1,360));img.setScaleType(ImageView.ScaleType.CENTER_CROP);img.setContentDescription("عکس "+m.name);try{img.setImageURI(Uri.parse(m.imageUri));}catch(Exception ignored){img.setBackgroundColor(Color.DKGRAY);}card.addView(img);}TextView t=new TextView(this);t.setText(m.name+"\n"+(m.dose==null?"":m.dose)+"\n⏰ "+String.format(Locale.US,"%02d:%02d",m.hour,m.minute)+"   📦 "+m.stock+"\n"+(today.equals(m.lastTakenDate)?"امروز مصرف شد ✅":"امروز مصرف نشده ❌"));t.setTextColor(0xfff8fafc);t.setTextSize(17);t.setGravity(Gravity.RIGHT);t.setPadding(0,14,0,8);card.addView(t);Button del=new Button(this);del.setText("حذف");del.setOnClickListener(v->{db.delete(m.id);render();});card.addView(del);list.addView(card);}}
 void openExactAlarmSettings(){if(Build.VERSION.SDK_INT>=31){try{startActivity(new Intent(Settings.ACTION_REQUEST_SCHEDULE_EXACT_ALARM,Uri.parse("package:"+getPackageName())));}catch(Exception e){startActivity(new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS,Uri.parse("package:"+getPackageName())));}}else Toast.makeText(this,"در این نسخه Android نیاز نیست",Toast.LENGTH_SHORT).show();}
}
